/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author Marcelo
 */
public class ExcluirFuncionario extends javax.swing.JFrame {
    
    DefaultListModel model = new DefaultListModel();
    UsuarioDAO u = UsuarioDAO.getInstance();
    List<Usuario> usuarios;
        
    public ExcluirFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    /*    
        String nome = null;
        usuarios = u.retrieveAll();
        try{
            int i = 0;
            while(usuarios.get(i).getNome() != null){
                nome = usuarios.get(i).getNome();
                //System.out.println(nome);
                setLstFuncionarios(nome);
                i++;
            }
        } catch(IndexOutOfBoundsException e){
            
        }*/   
    }

    public void addBtnCancelarListener(ActionListener btnCancelarListener){
        this.btnCancelar.addActionListener(btnCancelarListener);
    }
    
    public void setLstFuncionarios(String nome){
        
        model.addElement(nome);
        lstFuncionarios.setModel(model);

    }
    
    public ConfirmaExcluirFuncionario getConfirmaExcluirFuncFrame(){
    
        return new ConfirmaExcluirFuncionario();
    
    }
    
    public int selectedIndex(){
    
        return lstFuncionarios.getSelectedIndex();
        
    }
    
    public void setLstVoid(){
        model.clear();
    }
    
    public void relistar(){
        String nome = null;
        usuarios = u.retrieveAll();
            try{
                int i = 0;
                while(usuarios.get(i).getNome() != null){
                    nome = usuarios.get(i).getNome();
                    //System.out.println(nome);
                    setLstFuncionarios(nome);
                    i++;
                }
            } catch(IndexOutOfBoundsException e){

            }
    
    }
    
    public void excluirFuncionario(int a){
        List<Usuario> usu;
        String nomeFunc, set;
        UsuarioDAO u = UsuarioDAO.getInstance();
        ConfirmaExcluirFuncionario cef = new ConfirmaExcluirFuncionario();
        
        lstFuncionarios.setSelectedIndex(a);      
        nomeFunc = lstFuncionarios.getSelectedValue();
        //System.out.println(nomeFunc);
        usu = u.retrieveLike(nomeFunc);

        //System.out.println(usu.get(0).getNome());
        
        cef.setVisible(true);
            
        for(int i = 0; i < usu.size(); i++){
            
            set = cef.getFuncionarios(nomeFunc, usu.get(i).getCpf());
            cef.setList(set);
        }     
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDemitirFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionarios = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDemitirFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDemitirFuncionario.setText("Clique no Funcionário que deseja excluir");

        lstFuncionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstFuncionarios.setNextFocusableComponent(lstFuncionarios);
        lstFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFuncionarios);

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDemitirFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCancelar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDemitirFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFuncionariosMouseClicked
        // TODO add your handling code here:
        int a = selectedIndex();
        excluirFuncionario(a);
                
    }//GEN-LAST:event_lstFuncionariosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDemitirFuncionario;
    private javax.swing.JList<String> lstFuncionarios;
    // End of variables declaration//GEN-END:variables
}
