/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Dulcina
 */
public class PainelFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form PainelFuncionario
     */
    public PainelFuncionario() {
        initComponents();
    }
    
    public void addBtnCadastrarFuncListener(ActionListener listener){
    
        btnCadastrarFuncionario.addActionListener(listener);
        
    }
    
    public CadastrarFuncionario getCadastrarFuncFrame(){
    
        return new CadastrarFuncionario();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluirFuncionario = new javax.swing.JToggleButton();
        lblTituloFuncionarios = new javax.swing.JLabel();
        lblListaMetres = new javax.swing.JLabel();
        lblListaCaixas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMetres = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCaixas = new javax.swing.JList<>();
        btnCadastrarFuncionario = new javax.swing.JToggleButton();

        btnExcluirFuncionario.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluirFuncionario.setText("Excluir funcionário");

        lblTituloFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloFuncionarios.setText("Funcionários");

        lblListaMetres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListaMetres.setText("Metres");

        lblListaCaixas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListaCaixas.setText("Caixas");

        jScrollPane2.setViewportView(lstMetres);

        jScrollPane3.setViewportView(lstCaixas);

        btnCadastrarFuncionario.setBackground(new java.awt.Color(102, 255, 102));
        btnCadastrarFuncionario.setText("Cadastrar funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblListaMetres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblListaCaixas)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloFuncionarios)
                            .addComponent(btnCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnExcluirFuncionario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTituloFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListaCaixas)
                    .addComponent(lblListaMetres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirFuncionario)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrarFuncionario;
    private javax.swing.JToggleButton btnExcluirFuncionario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblListaCaixas;
    private javax.swing.JLabel lblListaMetres;
    private javax.swing.JLabel lblTituloFuncionarios;
    private javax.swing.JList<String> lstCaixas;
    private javax.swing.JList<String> lstMetres;
    // End of variables declaration//GEN-END:variables
}


