/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionarios;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author Dulcina
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFuncionario
     */
    public CadastrarFuncionario() {
        initComponents();
        setLocationRelativeTo(null);

    }
    
    public void addBtnCancelarListener(ActionListener btnCancelarListener){
        this.btnCancelar.addActionListener(btnCancelarListener);
    }
    
    public void addBtnCadastrarListener(ActionListener btnCadastrarListener){
        this.btnCadastrar.addActionListener(btnCadastrarListener);
    }
    
    public Integer getCargoFunc(){
        if(String.valueOf(cmbCargo.getSelectedItem()).compareTo("Caixa") == 0){
            return 1;
        }
        else if(String.valueOf(cmbCargo.getSelectedItem()).compareTo("Metre") == 0){
            return 2;
        }
        else {
            return 3;
        }
    }
    
    public String getNomeCompleto(){
        return txtNomeCompleto.getText();
    }
    
    public String getUsuario(){
        return txtUsuario.getText();
    }
    
    public String getSenha(){
        return String.valueOf(txtSenha.getPassword());
    }
    
    public String getCPF(){
        
        String cpf;
        String[] cpfTratado;
        
        cpf = txtCPF.getText();
        
        //System.out.println(CPF);
        cpfTratado = cpf.split("\\.");
        
        String digito = cpfTratado[2];
        String[] digitoE = digito.split("-");
        
        String CPFinal = cpfTratado[0] + cpfTratado[1] + digitoE[0] + digitoE[1];

        return CPFinal;
    }
    
    public String getCNPJ(){
        return txtCNPJ.getText();
    }
    
    public void setTextVoid(){
    
        txtNomeCompleto.setText("");
        txtCNPJ.setText("");
        txtCPF.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        lblCNPJ = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(366, 390));
        setMinimumSize(new java.awt.Dimension(366, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(366, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/button_cadastrar.png"))); // NOI18N
        btnCadastrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/button_cadastrar_clicked.png"))); // NOI18N
        btnCadastrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/button_cadastrar_swap.png"))); // NOI18N
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 143, 44));

        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 33, -1, -1));

        cmbCargo.setBackground(new java.awt.Color(255, 248, 244));
        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa", "Gerente", "Metre" }));
        getContentPane().add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 58, 265, 30));

        lblNomeCompleto.setText("Nome Completo");
        getContentPane().add(lblNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 106, -1, -1));

        txtNomeCompleto.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 126, 265, 30));

        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 167, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 187, 116, 30));

        lblCPF.setText("CPF");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 228, -1, -1));

        lblSenha.setText("Senha");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 228, -1, -1));

        txtSenha.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 248, 116, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar.png"))); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_clicked.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_swap.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 360, 75, 23));

        lblCNPJ.setText("CNPJ");
        getContentPane().add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 167, -1, -1));

        txtCNPJ.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 187, 116, 30));

        txtCPF.setBackground(new java.awt.Color(255, 248, 244));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 248, 116, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE366x390.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
