/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionarios;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoDAO;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author Talita-csl
 */
public class ExcluiFuncionario extends javax.swing.JFrame {

    DefaultTableModel modelo;
    /**
     * Creates new form ExcluiFuncionario
     */
    public ExcluiFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void excluirFuncionario (){
        
        try {
            int row = tblTabela.getSelectedRow();
            int column = tblTabela.getSelectedColumn();
            Object nome = tblTabela.getValueAt(row, 1);
            Object cpf = tblTabela.getValueAt(row, 2);

            //System.out.println(nome);
            //System.out.println(marca);
            UsuarioDAO udao = UsuarioDAO.getInstance();
            List<Usuario> usu;

            usu = udao.retrieveLike(nome.toString());
            String Nome = usu.get(0).getNome();
            String CPF = usu.get(0).getCpf();
            //System.out.println(Nome);
            //System.out.println(Marca);
            
            if(Nome.compareTo(nome.toString()) == 0 && CPF.compareTo(cpf.toString()) == 0){
                udao.delete(usu.get(0));
                JOptionPane.showMessageDialog(null, "Funcionário Excluido com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Funcionário não foi excluído, tente novamente");
            }
            
        } catch (IndexOutOfBoundsException e) {
        } catch (ClassCastException ex) {
        }
        
    }
    
    public void addBtnExcluirListener(ActionListener listener){
        this.btnExcluir.addActionListener(listener);
    }

    public void addBtnBuscarListener(ActionListener listener){
        this.btnBuscar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public String getNomeFunc(){
        return txtBuscarFuncionario.getText();
    }
    
    public void instanciarTabela(){
        modelo = (DefaultTableModel) tblTabela.getModel();
    }
    
    public void preencherTabela(Object [] o){

        modelo.addRow(new Object[]{o[0], o[1], o[2], o[3]});
        
    }
    
    public void limparTabela(){
        if(modelo.getRowCount() > 0){
            while(modelo.getRowCount() > 0)
            {
                modelo.removeRow(0);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarProduto = new javax.swing.JLabel();
        txtBuscarFuncionario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarProduto.setText("Excluir Funcionário");

        btnBuscar.setText("Buscar");

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        btnCancelar.setText("Cancelar");

        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblBuscarProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBuscarProduto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtBuscarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarProduto;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtBuscarFuncionario;
    // End of variables declaration//GEN-END:variables
}
