/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionarios;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoDAO;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author Talita-csl
 */
public class ExcluiFuncionario extends javax.swing.JFrame {

    DefaultTableModel modelo;
    /**
     * Creates new form ExcluiFuncionario
     */
    public ExcluiFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void excluirFuncionario (){
        
        try {
            int row = tblTabela.getSelectedRow();
            int column = tblTabela.getSelectedColumn();
            Object nome = tblTabela.getValueAt(row, 1);
            Object cpf = tblTabela.getValueAt(row, 2);

            //System.out.println(nome);
            //System.out.println(marca);
            UsuarioDAO udao = UsuarioDAO.getInstance();
            List<Usuario> usu;

            usu = udao.retrieveLike(nome.toString());
            String Nome = usu.get(0).getNome();
            String CPF = usu.get(0).getCpf();
            //System.out.println(Nome);
            //System.out.println(Marca);
            
            if(Nome.compareTo(nome.toString()) == 0 && CPF.compareTo(cpf.toString()) == 0){
                udao.delete(usu.get(0));
                JOptionPane.showMessageDialog(null, "Funcionário Excluido com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Funcionário não foi excluído, tente novamente");
            }
            
        } catch (IndexOutOfBoundsException e) {
        } catch (ClassCastException ex) {
        }
        
    }
    
    public void addBtnExcluirListener(ActionListener listener){
        this.btnExcluir.addActionListener(listener);
    }

    public void addBtnBuscarListener(ActionListener listener){
        this.btnBuscar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public String getNomeFunc(){
        return txtBuscarFuncionario.getText();
    }
    
    public void instanciarTabela(){
        modelo = (DefaultTableModel) tblTabela.getModel();
    }
    
    public void preencherTabela(Object [] o){

        modelo.addRow(new Object[]{o[0], o[1], o[2], o[3]});
        
    }
    
    public void limparTabela(){
        if(modelo.getRowCount() > 0){
            while(modelo.getRowCount() > 0)
            {
                modelo.removeRow(0);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarProduto = new javax.swing.JLabel();
        txtBuscarFuncionario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarProduto.setText("Excluir Funcionário");
        getContentPane().add(lblBuscarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 22, -1, -1));

        txtBuscarFuncionario.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtBuscarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 224, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Pequeno/button_buscar.png"))); // NOI18N
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Pequeno/button_buscar_clicked.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Pequeno/button_buscar_swap.png"))); // NOI18N
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 57, 108, 30));

        tblTabela.setBackground(new java.awt.Color(255, 248, 244));
        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTabela.setGridColor(new java.awt.Color(216, 201, 192));
        tblTabela.setSelectionBackground(new java.awt.Color(244, 216, 194));
        tblTabela.setSelectionForeground(new java.awt.Color(81, 56, 39));
        jScrollPane1.setViewportView(tblTabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 400, 108));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar.png"))); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_clicked.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_swap.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 260, 75, 23));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Pequeno/button_excluir.png"))); // NOI18N
        btnExcluir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Pequeno/button_excluir_clicked.png"))); // NOI18N
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Pequeno/button_excluir_swap.png"))); // NOI18N
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 75, 23));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE400x310.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarProduto;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtBuscarFuncionario;
    // End of variables declaration//GEN-END:variables
}
