/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.funcionarios;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author Dulcina
 */
public class PainelFuncionario extends javax.swing.JPanel {

    DefaultListModel modelC = new DefaultListModel();
    DefaultListModel modelM = new DefaultListModel();
    DefaultListModel modelVoid = new DefaultListModel();
    UsuarioDAO u = UsuarioDAO.getInstance();
    List<Usuario> usuarios;
    /**
     * Creates new form PainelFuncionario
     */
    public PainelFuncionario() {
        initComponents();
        
        String nome = null;
        usuarios = u.retrieveAll();
        try{
            int i = 0;
            while(usuarios.get(i).getNome() != null){
                nome = usuarios.get(i).getNome();
                //System.out.println(nome);
                setLstFuncionarios(i, nome);
                i++;
            }
        } catch(IndexOutOfBoundsException e){
            
        }
        
    }
    
    public void addBtnCadastrarFuncListener(ActionListener listener){
    
        btnCadastrarFuncionario.addActionListener(listener);
        
    }
    
    public CadastrarFuncionario getCadastrarFuncFrame(){
    
        return new CadastrarFuncionario();
    
    }
    
    public void addBtnExcluirFuncListener(ActionListener listener){
    
        btnExcluirFuncionario.addActionListener(listener);
        
    }
    
    public ExcluiFuncionario getExcluiFuncFrame(){
    
        return new ExcluiFuncionario();
    
    }
    
    public void setLstVoid(){
        modelM.clear();
        modelC.clear();
    }
    
    public void relistar(){
        String nome = null;
        usuarios = u.retrieveAll();
            try{
                int i = 0;
                while(usuarios.get(i).getNome() != null){
                    nome = usuarios.get(i).getNome();
                    //System.out.println(nome);
                    setLstFuncionarios(i, nome);
                    i++;
                }
            } catch(IndexOutOfBoundsException e){

            }
    
    }
    
    public void setLstFuncionarios(int i, String nome){

        if(usuarios.get(i).getTipoUsuario() == 2){
            modelM.addElement(nome);
            lstMetres.setModel(modelM);
        }
        else if(usuarios.get(i).getTipoUsuario() == 1){
            modelC.addElement(nome);
            lstCaixas.setModel(modelC);
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluirFuncionario = new javax.swing.JToggleButton();
        lblTituloFuncionarios = new javax.swing.JLabel();
        lblListaMetres = new javax.swing.JLabel();
        lblListaCaixas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMetres = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCaixas = new javax.swing.JList<>();
        btnCadastrarFuncionario = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(540, 350));
        setPreferredSize(new java.awt.Dimension(540, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExcluirFuncionario.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Funcionário/button_excluir-funcionario.png"))); // NOI18N
        btnExcluirFuncionario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Funcionário/button_excluir-funcionario_clicked.png"))); // NOI18N
        btnExcluirFuncionario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/Funcionário/button_excluir-funcionario_swap.png"))); // NOI18N
        add(btnExcluirFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 119, 23));

        lblTituloFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/funcionarios.png"))); // NOI18N
        lblTituloFuncionarios.setText(" ");
        add(lblTituloFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 380, -1));

        lblListaMetres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListaMetres.setText("Metres");
        add(lblListaMetres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblListaCaixas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListaCaixas.setText("Caixas");
        add(lblListaCaixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        lstMetres.setBackground(new java.awt.Color(255, 248, 244));
        lstMetres.setSelectionBackground(new java.awt.Color(244, 216, 194));
        lstMetres.setSelectionForeground(new java.awt.Color(81, 56, 39));
        jScrollPane2.setViewportView(lstMetres);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 140, 100));

        lstCaixas.setBackground(new java.awt.Color(255, 248, 244));
        lstCaixas.setSelectionBackground(new java.awt.Color(244, 216, 194));
        lstCaixas.setSelectionForeground(new java.awt.Color(81, 56, 39));
        jScrollPane3.setViewportView(lstCaixas);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 140, 100));

        btnCadastrarFuncionario.setBackground(new java.awt.Color(102, 255, 102));
        btnCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/Funcionário/button_cadastrar-funcionario.png"))); // NOI18N
        btnCadastrarFuncionario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/Funcionário/button_cadastrar-funcionario_clicked.png"))); // NOI18N
        btnCadastrarFuncionario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cadastrar/Funcionário/button_cadastrar-funcionario_swap.png"))); // NOI18N
        add(btnCadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 540, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrarFuncionario;
    private javax.swing.JToggleButton btnExcluirFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblListaCaixas;
    private javax.swing.JLabel lblListaMetres;
    private javax.swing.JLabel lblTituloFuncionarios;
    private javax.swing.JList<String> lstCaixas;
    private javax.swing.JList<String> lstMetres;
    // End of variables declaration//GEN-END:variables
}


