/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mesas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;

/**
 *
 * @author Rafael
 */
public class ExcluirReserva extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirReserva
     */
    public ExcluirReserva() {
        initComponents();
        CenteredFrame(this);
        
    }
    
    public int getMesa(){
        
        String mesa = String.valueOf(this.cmbMesa.getSelectedItem());
        
        if(mesa.compareTo("Mesa 1") == 0)
            return 1;
        else if(mesa.compareTo("Mesa 2") == 0)
            return 2;
        else if(mesa.compareTo("Mesa 3") == 0)
            return 3;
        else if(mesa.compareTo("Mesa 4") == 0)
            return 4;
        else if(mesa.compareTo("Mesa 5") == 0)
            return 5;
        else
            return 6;
        
    }

    public String getDataHora(){
        return txtDataHora.getText() + ":00";
    }
    
    public void addBtnConfirmarListener(ActionListener listener){
        this.btnConfirmar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener) {
        this.btnCancelar.addActionListener(listener);
    }
    
    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExcluirReserva = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        cmbMesa = new javax.swing.JComboBox<>();
        lblDataHora = new javax.swing.JLabel();
        txtDataHora = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExcluirReserva.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblExcluirReserva.setText("Excluir Reserva");
        getContentPane().add(lblExcluirReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 40, -1, -1));

        lblMesa.setText("Mesa");
        getContentPane().add(lblMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 101, -1, -1));

        cmbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4", "Mesa 5", "Mesa 6", "Mesa 7" }));
        getContentPane().add(cmbMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 121, 263, 30));

        lblDataHora.setText("Data/hora da reserva");
        getContentPane().add(lblDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 169, -1, -1));

        txtDataHora.setBackground(new java.awt.Color(255, 244, 248));
        try {
            txtDataHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 189, 263, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel3.setText("aaaa/mm/dd hh:mm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 169, -1, 14));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar.png"))); // NOI18N
        btnConfirmar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar_clicked.png"))); // NOI18N
        btnConfirmar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar_swap.png"))); // NOI18N
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 158, 30));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblExcluirReserva;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JFormattedTextField txtDataHora;
    // End of variables declaration//GEN-END:variables
}
