/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mesas;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Rafael
 */
public class ReservaMesa extends javax.swing.JFrame {

    /**
     * Creates new form ReservaMesa
     */
    public ReservaMesa() {
        initComponents();
        CenteredFrame(this);
        setColors(spnMesa, new Color(255,248,244));
        setColors(spnPessoas, new Color(255,248,244));
    }
    
    private static void setColors(JSpinner spinner, Color background)
    {
        JComponent editor = spinner.getEditor();
        System.out.println("Editor "+editor);
        int n = editor.getComponentCount();
        for (int i=0; i<n; i++)
        {
            Component c = editor.getComponent(i);
            System.out.println("Component "+i+": "+c);
            if (c instanceof JTextField)
            {
                c.setBackground(background);
            }
        }
    }

    public void addBtnConfirmarListener(ActionListener listener){
        this.btnConfirmar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public String getNome(){
        return this.txtNome.getText();
    }
    
    public int getMesa(){
        return (Integer) this.spnMesa.getValue();
    }
    
    public int getPessoas(){
        return (Integer) this.spnPessoas.getValue();
    }
    
    public String getDataHora(){
        return this.txtDataHora.getText();
    }
    
    public String getTelefone(){
        return this.txtTelefone.getText();
    }
    
    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        spnMesa = new javax.swing.JSpinner();
        lblDataHora = new javax.swing.JLabel();
        txtDataHora = new javax.swing.JFormattedTextField();
        lblPessoas = new javax.swing.JLabel();
        spnPessoas = new javax.swing.JSpinner();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva de Mesa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reserv_mesa.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, -1));

        txtNome.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 89, 297, 30));

        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 69, -1, -1));

        lblMesa.setText("Mesa");
        getContentPane().add(lblMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 165, -1, -1));
        getContentPane().add(spnMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 157, 37, 30));

        lblDataHora.setText("Data/Hora");
        getContentPane().add(lblDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 165, -1, -1));

        txtDataHora.setBackground(new java.awt.Color(255, 248, 244));
        try {
            txtDataHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 157, 98, 30));

        lblPessoas.setText("Pessoas");
        getContentPane().add(lblPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 213, -1, -1));
        getContentPane().add(spnPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 205, 37, 30));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar.png"))); // NOI18N
        btnConfirmar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar_clicked.png"))); // NOI18N
        btnConfirmar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Confirmar/button_confirmar_swap.png"))); // NOI18N
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 263, 158, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar.png"))); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_clicked.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_swap.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 267, 75, 23));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel2.setText("aaaa/mm/dd hh:mm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 137, 98, 14));

        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 213, -1, -1));

        txtTelefone.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 205, 98, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPessoas;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JSpinner spnMesa;
    private javax.swing.JSpinner spnPessoas;
    private javax.swing.JFormattedTextField txtDataHora;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
