/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.itens;

import java.awt.event.ActionListener;

/**
 *
 * @author Rafael
 */
public class PainelItens extends javax.swing.JPanel {

    /**
     * Creates new form PainelItens
     */
    public PainelItens() {
        initComponents();
    }

    public void addBtnAdicionarListener(ActionListener listener){
        this.btnAdicionar.addActionListener(listener);
    }
    
    public void addBtnBuscarListener(ActionListener listener){
        this.btnBuscar.addActionListener(listener);
    }
    
    public void addBtnAlterarListener(ActionListener listener){
        this.btnAlterar.addActionListener(listener);
    }
    
    public void addBtnExcluirListener(ActionListener listener){
        this.btnExcluir.addActionListener(listener);
    }
    
    public MenuAdicionarItens getMenuAdicionar(){
        return new MenuAdicionarItens();
    }
    
    public MenuBuscarItens getMenuBuscar(){
        return new MenuBuscarItens();
    }
    
    public MenuAlterarItens getMenuAlterar(){
        return new MenuAlterarItens();
    }
    
    public MenuExcluirItens getMenuExcluir(){
        return new MenuExcluirItens();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblTituloItens = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(540, 350));
        setMinimumSize(new java.awt.Dimension(540, 350));
        setPreferredSize(new java.awt.Dimension(540, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar.png"))); // NOI18N
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar_clicked.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar_swap.png"))); // NOI18N
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 112, 45));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar.png"))); // NOI18N
        btnAlterar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar_clicked.png"))); // NOI18N
        btnAlterar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar_swap.png"))); // NOI18N
        add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 112, 45));

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir.png"))); // NOI18N
        btnExcluir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir_clicked.png"))); // NOI18N
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir_swap.png"))); // NOI18N
        add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 112, 45));

        lblTituloItens.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/itens.png"))); // NOI18N
        add(lblTituloItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 280, 120));

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar.png"))); // NOI18N
        btnAdicionar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar_clicked.png"))); // NOI18N
        btnAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar_swap.png"))); // NOI18N
        add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 390, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTituloItens;
    // End of variables declaration//GEN-END:variables
}
