/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estoque;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoDAO;

/**
 *
 * @author Dulcina
 */
public class PainelAlterarProduto extends javax.swing.JFrame {
    
    DefaultTableModel modelo;

    public PainelAlterarProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    
    public void addBtnBuscarListener(ActionListener listener){
        this.btnBuscar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public void addBtnEditarListener(ActionListener listener){
        this.btnEditar.addActionListener(listener);
    }
    
    public void instanciarTabela(){
        modelo = (DefaultTableModel) tblTabela.getModel();
    }
    
    public void preencherTabela(Object [] o){

        modelo.addRow(new Object[]{o[0], o[1], o[2], o[3]});
        
    }
    
    public void limparTabela(){
        if(modelo.getRowCount() > 0){
            while(modelo.getRowCount() > 0)
            {
                modelo.removeRow(0);
            }
        }
    }
    
    public String getNomeProd(){
        return txtBuscarProduto.getText();
    }
    
    public String editarProduto (){
        
        try {
            
            boolean resposta = false;
            int row = tblTabela.getSelectedRow();
            int column = tblTabela.getSelectedColumn();
            Object nome = tblTabela.getValueAt(row, 0);
            Object marca = tblTabela.getValueAt(row, 1);

            //System.out.println(nome);
            //System.out.println(marca);
            ProdutoDAO pdao = ProdutoDAO.getInstance();
            List<Produto> prod;

            prod = pdao.retrieveLike(nome.toString());
            String Nome = prod.get(0).getNome();
            String Marca = prod.get(0).getMarca();
            //System.out.println(Nome);
            //System.out.println(Marca);
            
            if(Nome.compareTo(nome.toString()) == 0 && Marca.compareTo(marca.toString()) == 0){
                return nome.toString();
                
                //JOptionPane.showMessageDialog(null, "Produto Excluido com sucesso!");
            }
            else{
                
                
            }
            
        } catch (IndexOutOfBoundsException e) {
        } catch (ClassCastException ex) {
        }
        String a = "";
        return a;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        lblAlterarProduto = new javax.swing.JLabel();
        txtBuscarProduto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditar.setText("Editar");

        lblAlterarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAlterarProduto.setText("Alterar Produto");

        btnBuscar.setText("Buscar");

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Marca", "Fornecedor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblAlterarProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(63, 63, 63))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAlterarProduto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlterarProduto;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtBuscarProduto;
    // End of variables declaration//GEN-END:variables
}
