/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estoque;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoDAO;

/**
 *
 * @author Dulcina
 */
public class PainelAlterarProduto extends javax.swing.JFrame {
    
    DefaultTableModel modelo;

    public PainelAlterarProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    
    public void addBtnBuscarListener(ActionListener listener){
        this.btnBuscar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public void addBtnEditarListener(ActionListener listener){
        this.btnEditar.addActionListener(listener);
    }
    
    public void instanciarTabela(){
        modelo = (DefaultTableModel) tblTabela.getModel();
    }
    
    public void preencherTabela(Object [] o){

        modelo.addRow(new Object[]{o[0], o[1], o[2], o[3]});
        
    }
    
    public void limparTabela(){
        if(modelo.getRowCount() > 0){
            while(modelo.getRowCount() > 0)
            {
                modelo.removeRow(0);
            }
        }
    }
    
    public String getNomeProd(){
        return txtBuscarProduto.getText();
    }
    
    public String editarProduto (){
        
        try {
            
            boolean resposta = false;
            int row = tblTabela.getSelectedRow();
            int column = tblTabela.getSelectedColumn();
            Object nome = tblTabela.getValueAt(row, 0);
            Object marca = tblTabela.getValueAt(row, 1);

            //System.out.println(nome);
            //System.out.println(marca);
            ProdutoDAO pdao = ProdutoDAO.getInstance();
            List<Produto> prod;

            prod = pdao.retrieveLike(nome.toString());
            String Nome = prod.get(0).getNome();
            String Marca = prod.get(0).getMarca();
            //System.out.println(Nome);
            //System.out.println(Marca);
            
            if(Nome.compareTo(nome.toString()) == 0 && Marca.compareTo(marca.toString()) == 0){
                return nome.toString();
                
                //JOptionPane.showMessageDialog(null, "Produto Excluido com sucesso!");
            }
            else{
                
                
            }
            
        } catch (IndexOutOfBoundsException e) {
        } catch (ClassCastException ex) {
        }
        String a = "";
        return a;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        lblAlterarProduto = new javax.swing.JLabel();
        txtBuscarProduto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Editar/button_editar.png"))); // NOI18N
        btnEditar.setMaximumSize(new java.awt.Dimension(75, 23));
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Editar/button_editar_clicked.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Editar/button_editar_swap.png"))); // NOI18N
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 260, 75, 23));

        lblAlterarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/alt_prod.png"))); // NOI18N
        lblAlterarProduto.setText(" ");
        getContentPane().add(lblAlterarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, -1));

        txtBuscarProduto.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtBuscarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 224, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Buscar Pequeno/button_buscar.png"))); // NOI18N
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Buscar Pequeno/button_buscar_clicked.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/Buscar Pequeno/button_buscar_swap.png"))); // NOI18N
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 108, 30));

        tblTabela.setBackground(new java.awt.Color(255, 248, 244));
        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Marca", "Fornecedor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTabela.setGridColor(new java.awt.Color(216, 201, 192));
        tblTabela.setSelectionBackground(new java.awt.Color(244, 216, 194));
        tblTabela.setSelectionForeground(new java.awt.Color(81, 56, 39));
        jScrollPane1.setViewportView(tblTabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 400, 108));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar.png"))); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_clicked.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_swap.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 260, 75, 23));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE400x310.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlterarProduto;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtBuscarProduto;
    // End of variables declaration//GEN-END:variables
}
