/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estoque;

import java.awt.event.ActionListener;

/**
 *
 * @author Talita-csl
 */
public class PainelEstoque extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstoque
     */
    public PainelEstoque() {
        initComponents();
    }
    
    public void addBtnAdicionarProdutoListener(ActionListener adicionarListener){
        this.btnAdicionarProduto.addActionListener(adicionarListener);
    }
    
    public void addBtnBuscarProdutoListener(ActionListener buscarListener){
        this.btnBuscarProduto.addActionListener(buscarListener);
    }
    
    public void addBtnAlterarProdutoListener(ActionListener alterarListener){
        this.btnAlterarProduto.addActionListener(alterarListener);
    }
    
    public void addBtnExcluirProdutoListener(ActionListener excluirListener){
        this.btnExcluirProduto.addActionListener(excluirListener);
    }
    
    public PainelAdicionarProduto getPainelAdicionar(){
        return new PainelAdicionarProduto();
    }
    
    public PainelBuscarProduto getPainelBuscar(){
        return new PainelBuscarProduto();
    }
    
    public PainelEditarProduto getPainelEditar(){
        return new PainelEditarProduto();
    }
    
    public PainelExcluirProduto getPainelExcluir(){
        return new PainelExcluirProduto();
    }
    public PainelAlterarProduto getPainelAlterar() {
        return new PainelAlterarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        lblTituloItens = new javax.swing.JLabel();
        btnAdicionarProduto = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(535, 362));
        setMinimumSize(new java.awt.Dimension(535, 362));
        setPreferredSize(new java.awt.Dimension(535, 362));

        btnBuscarProduto.setText("Buscar");

        btnAlterarProduto.setText("Alterar");

        btnExcluirProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirProduto.setText("Excluir");

        lblTituloItens.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloItens.setText("Controle de Estoque");

        btnAdicionarProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarProduto.setText("Adicionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTituloItens)))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTituloItens, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JLabel lblTituloItens;
    // End of variables declaration//GEN-END:variables
}

