/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estoque;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Dulcina
 */
public class PainelEditarProduto extends javax.swing.JFrame {

    public PainelEditarProduto() {
        initComponents();
        setLocationRelativeTo(null);
        setColors(spnQuantidade, new Color(255,248,244));
    }
    
    private static void setColors(JSpinner spinner, Color background)
    {
        JComponent editor = spinner.getEditor();
        System.out.println("Editor "+editor);
        int n = editor.getComponentCount();
        for (int i=0; i<n; i++)
        {
            Component c = editor.getComponent(i);
            System.out.println("Component "+i+": "+c);
            if (c instanceof JTextField)
            {
                c.setBackground(background);
            }
        }
    }
    
    public void addBtnSalvarListener(ActionListener listener){
        this.btnSalvar.addActionListener(listener);
    }
    
    public void addBtnCancelarListener(ActionListener listener){
        this.btnCancelar.addActionListener(listener);
    }
    
    public String getNomeProduto(){
        return txtNome.getText();
    }
    
    public void setNomeProduto(String nome){
        txtNome.setText(nome);
    }
    
    public String getMarcaProduto(){
        return txtMarca.getText();
    }
    
    public void setMarcaProduto(String nome){
        txtMarca.setText(nome);
    }
    
    public String getFornecedorProduto(){
        return txtFornecedor.getText();
    }
    
    public void setFornecedorProduto(String nome){
        txtFornecedor.setText(nome);
    }

    public int getQuantidadeProduto(){
        return (Integer)spnQuantidade.getValue();
    }
    
    public void setQuantidadeProduto(int nome){
        spnQuantidade.setValue(nome);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        lblEditarProduto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar.png"))); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_clicked.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Cancelar/button_cancelar_swap.png"))); // NOI18N
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 276, 75, 23));

        txtNome.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 62, 317, 27));

        txtMarca.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, 317, 27));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Salvar Alterações/button_salvar-alteracoes.png"))); // NOI18N
        btnSalvar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Salvar Alterações/button_salvar-alteracoes_clicked.png"))); // NOI18N
        btnSalvar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Salvar Alterações/button_salvar-alteracoes_swap.png"))); // NOI18N
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 231, 142, 59));

        lblFornecedor.setText("Fornecedor");
        getContentPane().add(lblFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 158, -1, -1));

        txtFornecedor.setBackground(new java.awt.Color(255, 248, 244));
        getContentPane().add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 178, 317, 27));

        lblQuantidade.setText("Quantidade");
        getContentPane().add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 211, -1, -1));
        getContentPane().add(spnQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 231, 159, 27));

        lblEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEditarProduto.setText("Editar Produto");
        getContentPane().add(lblEditarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 19, -1, -1));

        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 42, -1, -1));

        lblMarca.setText("Marca");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE400x310.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEditarProduto;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
