/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estoque;

import java.awt.event.ActionListener;

/**
 *
 * @author Talita-csl
 */
public class PainelEstoque extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstoque
     */
    public PainelEstoque() {
        initComponents();
    }
    
    public void addBtnAdicionarProdutoListener(ActionListener adicionarListener){
        this.btnAdicionarProduto.addActionListener(adicionarListener);
    }
    
    public void addBtnBuscarProdutoListener(ActionListener buscarListener){
        this.btnBuscarProduto.addActionListener(buscarListener);
    }
    
    public void addBtnAlterarProdutoListener(ActionListener alterarListener){
        this.btnAlterarProduto.addActionListener(alterarListener);
    }
    
    public void addBtnExcluirProdutoListener(ActionListener excluirListener){
        this.btnExcluirProduto.addActionListener(excluirListener);
    }
    
    public PainelAdicionarProduto getPainelAdicionar(){
        return new PainelAdicionarProduto();
    }
    
    public PainelBuscarProduto getPainelBuscar(){
        return new PainelBuscarProduto();
    }
    
    public PainelEditarProduto getPainelEditar(){
        return new PainelEditarProduto();
    }
    
    public PainelExcluirProduto getPainelExcluir(){
        return new PainelExcluirProduto();
    }
    public PainelAlterarProduto getPainelAlterar() {
        return new PainelAlterarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        lblTituloItens = new javax.swing.JLabel();
        btnAdicionarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(535, 362));
        setMinimumSize(new java.awt.Dimension(535, 362));
        setPreferredSize(new java.awt.Dimension(535, 362));
        setLayout(null);

        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar.png"))); // NOI18N
        btnBuscarProduto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar_clicked.png"))); // NOI18N
        btnBuscarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Buscar/button_buscar_swap.png"))); // NOI18N
        add(btnBuscarProduto);
        btnBuscarProduto.setBounds(54, 237, 112, 45);

        btnAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar.png"))); // NOI18N
        btnAlterarProduto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar_clicked.png"))); // NOI18N
        btnAlterarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Alterar/button_alterar_swap.png"))); // NOI18N
        add(btnAlterarProduto);
        btnAlterarProduto.setBounds(193, 237, 112, 45);

        btnExcluirProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir.png"))); // NOI18N
        btnExcluirProduto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir_clicked.png"))); // NOI18N
        btnExcluirProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Excluir/button_excluir_swap.png"))); // NOI18N
        add(btnExcluirProduto);
        btnExcluirProduto.setBounds(332, 237, 112, 45);

        lblTituloItens.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloItens.setText("Controle de Estoque");
        add(lblTituloItens);
        lblTituloItens.setBounds(137, 62, 241, 28);

        btnAdicionarProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar.png"))); // NOI18N
        btnAdicionarProduto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar_clicked.png"))); // NOI18N
        btnAdicionarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Botões/Adicionar/button_adicionar_swap.png"))); // NOI18N
        add(btnAdicionarProduto);
        btnAdicionarProduto.setBounds(54, 168, 390, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Estilo/Redimensionadas/pexels-photo-349610RE.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 540, 370);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTituloItens;
    // End of variables declaration//GEN-END:variables
}

